### ISSUE TITLE
Cooldown Timer Support

### ISSUE THREAD

**Issue by instafluff** [instafluff/ComfyJS#5]
It will be nice to add a timer cooldown to the `extra` parameter for onCommand() that includes the time since the individual user has used the command (user cooldown) and the time since any user has used the command (global cooldown) so that it would be easy for the Comfy.JS user to skip handling commands that are longer than X amount of time. Implementation details are still open for ideas too!

**Comment by Chopinsky** [comment]
I'm interested in implementing this feature. So if I'm understanding correctly, it sounds like that we would want to save the user interaction with the commands in a global variable, and then pass the time-passed-since-last value to the end user implementation of the `onCommand` function, i.e. to this line: https://github.com/instafluff/ComfyJS/blob/7a33e5258beb6f66d1e050c12d8c7ec112ba770a/app.js#L208

**Comment by instafluff** [comment]
That sounds like a great way to do it!

**Comment by Chopinsky** [comment]
Great, I'll see what I can do about it!

**Comment by talk2MeGooseman** [comment]
@instafluff can you release new version with this feature? Want to use it ASAP! ![bitmoji](https://render.bitstrips.com/v2/cpanel/fe4a1c10-cce9-4b4a-a43c-6e707afcc5d1-7bce6184-0c67-4209-b976-bec06e1848e6-v1.png?transparent=1&palette=1&width=246)

**Comment by instafluff** [comment]
Thanks for reminding me @talk2MeGooseman ! It was done with 176bb2018151961a9cebc58f9e40b2f773ffa419 and 1.0.12 is now published!
